FROM python:3.11-slim

WORKDIR /app

RUN pip install uv

COPY pyproject.toml uv.lock ./

RUN uv sync

COPY . .

CMD ["uv", "run", "fastapi", "run", "service.py", "--host", "0.0.0.0", "--port", "8000"]
